sudo: false

language: ruby
cache: bundler

before_script:
  - psql -c 'create database bookyt_test' -U postgres
  - bundle exec rake bookyt:travis
  - bundle exec rake db:schema:load

env:
  - DB=postgresql

script: "bundle exec rake spec"

rvm:
  - 2.2.2
  - 2.3.3

bundler_args: "--binstubs --without development"

# IRC notification
notifications:
  irc: "irc.freenode.org#cyt"
